const data=[

    { id: 1,
      Rollno  : "21ucc041" ,
      Name : "Gaurav Agrawal",
      Activeb : "none",
      approve: true,
      Phoneno:" 11324234" ,
      Gender: "Male",
      branch : "cce"
    },
    { id: 2,
      Rollno  : "21ucc041" ,
      Name : "Gaurav Agrawal",
      Activeb : "None",
      approve: true,
      Phoneno:" 11324234" ,
      Gender: "Male",
      branch : "cce"
    },
    { id: 3,
      Rollno  : "21ucc041" ,
      Name : "Gaurav Agrawal",
      Activeb : "none",
      approve: true,
      Phoneno:" 11324234" ,
      Gender: "Male",
      branch : "cce"
    },
    { id: 4,
      Rollno  : "21ucc041" ,
      Name : "Gaurav Agrawal",
      Activeb : "none",
      approve: true,
      Phoneno:" 11324234" ,
      Gender: "Male",
      branch : "cce"
    },
    { id: 5,
      Rollno  : "21ucc041" ,
      Name : "Gaurav Agrawal",
      Activeb : "none",
      approve: true,
      Phoneno:" 11324234" ,
      Gender: "Male",
      branch : "cce"
    },
    { id: 6,
      Rollno  : "21ucc041" ,
      Name : "Gaurav Agrawal",
      Activeb : "none",
      approve: true,
      Phoneno:" 11324234" ,
      Gender: "Male",
      branch : "cce"
    },
    { id: 7,
      Rollno  : "21ucc041" ,
      Name : "Gaurav Agrawal",
      Activeb : "none",
      approve: true,
      Phoneno:" 11324234" ,
      Gender: "Male",
      branch : "cce"
    }, 
    { id: 8,
      Rollno  : "21ucc041" ,
      Name : "Gaurav Agrawal",
      Activeb : "sem 1: clp sem 2: vee sem 1: clp sem 2: vee",
      approve: false,
      Phoneno:" 11324234" ,
      Gender: "Male",
      branch : "cce"
    },
    { id: 9,
      Rollno  : "21ucc041" ,
      Name : "Gaurav Agrawal",
      Activeb : "cp",
      approve: false,
      Phoneno:" 11324234" ,
      Gender: "Male",
      branch : "cce"
    },
    { id: 10,
      Rollno  : "21ucc041" ,
      Name : "Gaurav Agrawal",
      Activeb : "Be",
      approve: false,
      Phoneno:" 11324234" ,
      Gender: "Male",
      branch : "cce"
    },
    { id: 11,
      Rollno  : "21ucc041" ,
      Name : "Gaurav Agrawal",
      Activeb : "tce",
      approve: false,
      Phoneno:" 11324234" ,
      Gender: "Male",
      branch : "cce"
    },
    { id: 12,
      Rollno  : "21ucc041" ,
      Name : "Gaurav Agrawal",
      Activeb : "asd",
      approve: false,
      Phoneno:" 11324234" ,
      Gender: "Male",
      branch : "cce"
    },
    { id: 13,
      Rollno  : "21ucc041" ,
      Name : "Gaurav Agrawal",
      Activeb : "be-lab",
      approve: false,
      Phoneno:" 11324234" ,
      Gender: "Male",
      branch : "cce"
    },
    { id: 14,
      Rollno  : "21ucc041" ,
      Name : "Gaurav Agrawal",
      Activeb : "xyz"
      ,
      approve: false,
      Phoneno:" 11324234" ,
      Gender: "Male",
      branch : "cce"
    }]
    export default data;